# 从numpy得到Tensor

In [2]:
import tensorflow as tf
import numpy as np

# 创建一个numpy数组
a = np.array([1, 2, 3])

In [3]:
tf.convert_to_tensor(np.ones([2,3]))

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]])>

In [4]:
tf.convert_to_tensor(np.zeros([3,3]))

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])>

In [5]:
tf.convert_to_tensor([1,2])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [6]:
tf.convert_to_tensor([1,2], dtype=tf.float32)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [7]:
# 按列
tf.convert_to_tensor([[2],[3]] ,dtype=tf.float32)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [3.]], dtype=float32)>

In [8]:
# 初始化为0
tf.zeros([])

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [9]:
tf.zeros([1])

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>

In [10]:
tf.zeros([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [11]:
tf.zeros([2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [12]:
a = tf.zeros([2,3])
tf.zeros_like(a)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [13]:
tf.fill([2,3], 9)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[9, 9, 9],
       [9, 9, 9]], dtype=int32)>

In [14]:
# Random Permutation
idx = tf.range(10)
tf.random.shuffle(idx)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 7, 2, 3, 5, 1, 6, 4, 8, 9], dtype=int32)>

In [15]:
a = tf.random.normal([10,784])
b = tf.random.uniform([10], maxval=10, dtype=tf.int32)
b

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([9, 9, 5, 0, 7, 6, 5, 6, 0, 8], dtype=int32)>

这段代码使用了 TensorFlow 的随机数生成函数来创建两个张量 `a` 和 `b`，它们分别具有不同的形状和数据类型。以下是对每一行代码的详细解释：

### 第一行代码
```python
a = tf.random.normal([10,784])
```
这行代码生成了一个形状为 `[10, 784]` 的张量 `a`，其中的值是从标准正态分布（均值为 0，标准差为 1）中随机采样的。  
- `tf.random.normal` 是 TensorFlow 提供的一个函数，用于生成服从正态分布的随机数。
- 参数 `[10, 784]` 指定了张量的形状，其中 `10` 表示有 10 行，`784` 表示每行有 784 个元素。这种形状通常出现在机器学习任务中，例如处理图像数据时，每一行可能表示一个样本的特征向量。
- 默认情况下，生成的随机数的均值为 0，标准差为 1。如果需要自定义均值或标准差，可以通过 `mean` 和 `stddev` 参数进行设置。

### 第二行代码
```python
b = tf.random.uniform([10], maxval=10, dtype=tf.int32)
```
这行代码生成了一个形状为 `[10]` 的张量 `b`，其中的值是从均匀分布中随机采样的整数。  
- `tf.random.uniform` 是 TensorFlow 提供的另一个随机数生成函数，用于生成服从均匀分布的随机数。
- 参数 `[10]` 指定了张量的形状，这里表示生成一个包含 10 个元素的一维张量。
- `maxval=10` 指定了生成的随机数的上限（不包括 10），因此生成的整数范围是 `[0, 10)`。
- `dtype=tf.int32` 指定了张量的数据类型为 32 位整数。如果不指定，默认生成的是浮点数。

### 总结
这两行代码通常用于深度学习任务中的数据准备阶段。例如，`a` 可以表示一个批次的输入数据，每一行是一个样本的特征向量；`b` 可以表示对应的标签，每个值是一个类别的整数编码。这种随机生成的数据常用于测试模型的输入输出逻辑或在没有真实数据时进行模拟实验。

In [16]:
# 使用 tf.gather 函数根据索引张量 idx 从张量 a 中提取对应的行
# 这里的 idx 是一个一维张量，表示要从 a 中提取的行的索引
tf.gather(a, idx)

<tf.Tensor: shape=(10, 784), dtype=float32, numpy=
array([[-0.6148276 ,  1.2829787 ,  0.7882927 , ..., -2.2798593 ,
        -0.74909276, -0.511759  ],
       [ 0.17948672, -0.20308031,  2.0066426 , ..., -1.0387201 ,
        -1.1096778 , -1.8054893 ],
       [-1.7875631 , -0.05166411,  1.5259551 , ...,  1.1795572 ,
         0.09714194,  1.0185186 ],
       ...,
       [-0.42696035, -1.3934318 ,  0.55900234, ...,  1.3999722 ,
        -0.30156636,  0.17851794],
       [-0.2559583 , -0.47620392,  0.7227903 , ...,  0.01023562,
         1.0936806 , -0.16867004],
       [ 0.59773433,  1.5207876 , -0.41163495, ..., -0.80793715,
         0.9183698 , -0.64536685]], dtype=float32)>

## LOSS

In [17]:
# 生成一个形状为 [4, 4] 的张量 out，其中的值是从均匀分布中随机采样的
out = tf.random.uniform([4,4])

# 创建一个一维张量 y，包含从 0 到 3 的整数
y = tf.range(4)

# 将一维张量 y 转换为独热编码，深度为 4
y = tf.one_hot(y, depth=4)
y

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [18]:
# 使用均方误差（Mean Squared Error, MSE）计算预测值 out 和真实值 y 之间的损失
loss = tf.keras.losses.mse(y, out)
loss

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.30107635, 0.4726325 , 0.58946234, 0.72581893], dtype=float32)>

In [19]:
# 计算损失的均值，得到最终的标量损失值
loss = tf.reduce_mean(loss)
loss

<tf.Tensor: shape=(), dtype=float32, numpy=0.52224755>

*解释 one_hot 方法*
`tf.one_hot` 方法用于将类别标签转换为独热编码（one-hot encoding）。独热编码是一种表示分类数据的方式，其中每个类别用一个长度为类别总数的向量表示，向量中只有一个位置为 1，其余位置为 0。

在代码中：
```python
y = tf.range(4)
y = tf.one_hot(y, depth=4)
```
- `tf.range(4)` 生成一个包含 `[0, 1, 2, 3]` 的一维张量，表示类别标签。
- `tf.one_hot(y, depth=4)` 将这些类别标签转换为独热编码，`depth=4` 指定了编码向量的长度（即类别总数）。

结果是一个形状为 `[4, 4]` 的张量，其中每一行是一个独热编码向量。例如：
```
[[1., 0., 0., 0.],
 [0., 1., 0., 0.],
 [0., 0., 1., 0.],
 [0., 0., 0., 1.]]
```

## Vector
y = w x + b <br>
b 就是bias，<br>
bias 是神经网络中的一个可训练参数，用于调整模型的输出。它的作用是引入一个偏移量，使模型能够更好地拟合数据，即使输入特征的值为零时，模型也能输出非零的结果。

In [20]:
from keras import layers

# 创建一个全连接层（Dense Layer），输出维度为10
net = layers.Dense(10)

# 构建网络层，输入形状为 (4, 8)
net.build((4, 8))

# 查看网络层的权重矩阵（kernel）
net.kernel

<tf.Variable 'kernel:0' shape=(8, 10) dtype=float32, numpy=
array([[ 0.36068094, -0.07948673,  0.0276435 , -0.14253971, -0.28167862,
         0.14237893,  0.2732129 , -0.23863623, -0.55732465,  0.5759995 ],
       [ 0.13967162, -0.14320442,  0.2029239 , -0.00665653, -0.565138  ,
         0.14558953, -0.04027653, -0.2553271 , -0.28796348, -0.2214205 ],
       [ 0.09705335,  0.5594096 ,  0.376683  ,  0.47571146, -0.5538509 ,
        -0.07113916, -0.44284523,  0.26988274,  0.4945612 ,  0.38103002],
       [ 0.38112062,  0.01149893,  0.09368652,  0.04835063,  0.29417896,
        -0.20501646,  0.02059054,  0.3108908 , -0.1384399 ,  0.03814352],
       [-0.28264078, -0.1590676 , -0.06910396, -0.25038597, -0.4724654 ,
         0.00528073,  0.40559328, -0.50707185, -0.44553757,  0.42218727],
       [ 0.1847592 ,  0.34623086, -0.24522942, -0.15470323,  0.04345989,
         0.28637427,  0.4971906 , -0.3345096 , -0.07875085,  0.4888854 ],
       [ 0.10389531, -0.05519903,  0.5169505 ,  0.4098127 

In [21]:
net.bias

<tf.Variable 'bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

## Matrix 矩阵

In [22]:
x = tf.random.normal([4, 784])
# tf.TensorShape([4, 784])
x

<tf.Tensor: shape=(4, 784), dtype=float32, numpy=
array([[ 1.0647231 , -1.3939265 , -1.170491  , ...,  0.24677674,
        -1.2931015 , -0.7812058 ],
       [-0.65485483,  0.46893322, -1.0090643 , ...,  0.70460606,
        -0.72365165,  2.1718946 ],
       [ 0.21642096,  0.2248637 ,  2.0813434 , ..., -0.34362376,
         0.19540316, -1.043587  ],
       [ 0.10299772, -0.75668144,  0.7103799 , ...,  0.7183968 ,
        -0.7801946 ,  1.7664802 ]], dtype=float32)>

In [23]:
net = layers.Dense(10)
net.build((4,784))

In [24]:
net(x).shape

TensorShape([4, 10])

In [25]:
net.kernel.shape

TensorShape([784, 10])

In [26]:
net.bias.shape

TensorShape([10])

### 解释 Matrix 代码和相关形状

#### 1. `x = tf.random.normal([4, 784])`
这行代码生成了一个形状为 `[4, 784]` 的张量 `x`，其中的值是从标准正态分布（均值为 0，标准差为 1）中随机采样的。  
- `tf.random.normal` 是 TensorFlow 提供的一个函数，用于生成服从正态分布的随机数。
- 参数 `[4, 784]` 指定了张量的形状，其中 `4` 表示有 4 行，`784` 表示每行有 784 个元素。
- 这种形状通常用于深度学习任务中，例如处理图像数据时，每一行可能表示一个样本的特征向量。

#### 2. `net` 的形状
`net` 是一个全连接层（Dense Layer），它的输出维度为 10。  
- 在代码中，`net.build((4, 784))` 指定了输入的形状为 `[4, 784]`，即每个输入样本有 784 个特征。
- 由于全连接层的输出维度为 10，因此 `net` 的输出形状为 `[4, 10]`，表示 4 个样本，每个样本有 10 个输出值。

#### 3. `net.kernel.shape`
`net.kernel` 是全连接层的权重矩阵，其形状为 `[784, 10]`。  
- 权重矩阵的形状由输入维度和输出维度决定：
  - 输入维度为 784（每个样本的特征数）。
  - 输出维度为 10（全连接层的输出数）。
- 因此，`net.kernel.shape` 为 `[784, 10]`。

#### 4. `net.bias.shape`
`net.bias` 是全连接层的偏置向量，其形状为 `[10]`。  
- 偏置向量的长度等于输出维度，即每个输出值对应一个偏置。
- 因此，`net.bias.shape` 为 `[10]`。

#### 总结
- `x` 是输入数据，形状为 `[4, 784]`。
- `net` 是一个全连接层，输入形状为 `[4, 784]`，输出形状为 `[4, 10]`。
- `net.kernel` 是权重矩阵，形状为 `[784, 10]`。
- `net.bias` 是偏置向量，形状为 `[10]`。

## Reshape

In [27]:
# 使用 tf.reshape 函数改变张量的形状
# tf.reshape 是 TensorFlow 中用于改变张量形状的函数，但不会改变数据本身的顺序。

# 创建一个形状为 [2, 3] 的张量
x = tf.constant([[1, 2, 3], [4, 5, 6]])
print("原始张量 x:")
print(x)

原始张量 x:
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [28]:
# 将张量 x 重塑为形状 [3, 2]
x_reshaped = tf.reshape(x, [3, 2])
print("\n重塑后的张量 x_reshaped (形状 [3, 2]):")
print(x_reshaped)


重塑后的张量 x_reshaped (形状 [3, 2]):
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [31]:
# 将张量 x 重塑为一维张量
# 注意：-1 表示自动推断维度大小，前提是其他维度的大小已知且总元素数量不变。
x_flattened = tf.reshape(x, [-1])
print("\n重塑后的张量 x_flattened (一维张量):")
print(x_flattened)


重塑后的张量 x_flattened (一维张量):
tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


In [32]:
# 将张量 x 重塑为形状 [1, 6]
x_reshaped_1_6 = tf.reshape(x, [1, 6])
print("\n重塑后的张量 x_reshaped_1_6 (形状 [1, 6]):")
print(x_reshaped_1_6)


重塑后的张量 x_reshaped_1_6 (形状 [1, 6]):
tf.Tensor([[1 2 3 4 5 6]], shape=(1, 6), dtype=int32)


## Transpose

In [35]:
a = tf.random.normal((4,3,2,1))
a.shape

TensorShape([4, 3, 2, 1])

In [36]:
a = tf.transpose(a)
a.shape

TensorShape([1, 2, 3, 4])

In [38]:
tf_3d_trans = tf.transpose(x)
tf_3d_trans.shape

TensorShape([3, 2])

In [39]:
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [40]:
tf_3d_trans

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>