# 索引和切片

In [1]:
import tensorflow as tf

# 创建一个 3x3 的张量
tensor = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("原始张量:")
print(tensor)

# 索引操作
# 获取第一行
first_row = tensor[0]
print("\n第一行:")
print(first_row)

# 获取最后一列
last_column = tensor[:, -1]
print("\n最后一列:")
print(last_column)

# 获取特定元素 (第二行，第三列)
specific_element = tensor[1, 2]
print("\n第二行第三列的元素:")
print(specific_element)

# 切片操作
# 获取前两行
first_two_rows = tensor[:2]
print("\n前两行:")
print(first_two_rows)

# 获取中间的 2x2 子张量
middle_subtensor = tensor[0:2, 1:3]
print("\n中间的 2x2 子张量:")
print(middle_subtensor)

# 使用步长进行切片
# 每隔一行和一列取一个元素
strided_tensor = tensor[::2, ::2]
print("\n步长为 2 的切片:")
print(strided_tensor)

原始张量:
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)

第一行:
tf.Tensor([1 2 3], shape=(3,), dtype=int32)

最后一列:
tf.Tensor([3 6 9], shape=(3,), dtype=int32)

第二行第三列的元素:
tf.Tensor(6, shape=(), dtype=int32)

前两行:
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

中间的 2x2 子张量:
tf.Tensor(
[[2 3]
 [5 6]], shape=(2, 2), dtype=int32)

步长为 2 的切片:
tf.Tensor(
[[1 3]
 [7 9]], shape=(2, 2), dtype=int32)


In [4]:
# 生成 TensorFlow 的张量
# 使用 tf.constant 创建一个 3x3 的张量
# 张量是 TensorFlow 中的基本数据结构，类似于多维数组
tensor = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("原始张量:")
print(tensor)

first_row = tensor[0]
print("\n第一行:")
print(first_row)
print("\n使用...:")
print(tensor[...])
print("\n使用 0, ...:")
print(tensor[0,...])
print("\n使用 ...,0:")
print(tensor[...,0])

原始张量:
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)

第一行:
tf.Tensor([1 2 3], shape=(3,), dtype=int32)

使用...:
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)

使用 0, ...:
tf.Tensor([1 2 3], shape=(3,), dtype=int32)

使用 ...,0:
tf.Tensor([1 4 7], shape=(3,), dtype=int32)


## tf.gather

In [9]:
import tensorflow as tf

# tf.gather 用于从张量的指定轴中根据索引提取切片
# 它的主要作用是从张量中提取特定的行、列或其他维度的子集

# 示例：从张量中提取特定的行或列

# 创建一个 3x3 的张量
tensor = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("原始张量:")
print(tensor)

原始张量:
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [10]:
# 使用 tf.gather 提取第 0 行和第 2 行
# 参数 axis=0 表示从行的维度提取
rows = tf.gather(tensor, indices=[0, 2], axis=0)
print("\n提取第 0 行和第 2 行:")
print(rows)


提取第 0 行和第 2 行:
tf.Tensor(
[[1 2 3]
 [7 8 9]], shape=(2, 3), dtype=int32)


In [ ]:
# 使用 tf.gather 提取第 1 列和第 2 列
# 参数 axis=1 表示从列的维度提取
columns = tf.gather(tensor, indices=[1, 2], axis=1)
print("\n提取第 1 列和第 2 列:")
print(columns)


提取第 1 列和第 2 列:
tf.Tensor(
[[2 3]
 [5 6]
 [8 9]], shape=(3, 2), dtype=int32)


In [15]:
# 示例：从 3D 张量中提取特定切片
tensor_3d = tf.constant([
  [[1, 2],   [3, 4],   [5, 6]],
  [[7, 8],   [9, 10],  [11, 12]],
  [[13, 14], [15, 16], [17, 18]]
])
print("\n3D 张量:")
print(tensor_3d)


3D 张量:
tf.Tensor(
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]], shape=(3, 3, 2), dtype=int32)


In [14]:
# 提取第 0 和第 2 个矩阵 (axis=0)
matrices = tf.gather(tensor_3d, indices=[0, 2], axis=0)
print("\n提取第 0 和第 2 个矩阵:")
print(matrices)



提取第 0 和第 2 个矩阵:
tf.Tensor(
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[13 14]
  [15 16]
  [17 18]]], shape=(2, 3, 2), dtype=int32)


In [12]:
# 提取每个矩阵的第 1 行 (axis=1)
rows_3d = tf.gather(tensor_3d, indices=[1], axis=1)
print("\n提取每个矩阵的第 1 行:")
print(rows_3d)


提取每个矩阵的第 1 行:
tf.Tensor(
[[[ 3  4]]

 [[ 9 10]]

 [[15 16]]], shape=(3, 1, 2), dtype=int32)


In [13]:
# 提取每行的第 0 列 (axis=2)
columns_3d = tf.gather(tensor_3d, indices=[0], axis=2)
print("\n提取每行的第 0 列:")
print(columns_3d)


提取每行的第 0 列:
tf.Tensor(
[[[ 1]
  [ 3]
  [ 5]]

 [[ 7]
  [ 9]
  [11]]

 [[13]
  [15]
  [17]]], shape=(3, 3, 1), dtype=int32)


## gather_nd

In [ ]:
# 使用 tf.gather_nd 提取张量 tensor_3d 中的特定位置的元素
# [0, 0] 表示提取第 0 个矩阵的第 0 行的第 0 列的元素
result = tf.gather_nd(tensor_3d, [0, 0])
print(result)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [ ]:
# 使用 tf.gather_nd 从 3D 张量中提取特定位置的元素
# [[0,1], [1,2]] 表示提取第 0 个矩阵的第 1 行和第 1 个矩阵的第 2 行
result = tf.gather_nd(tensor_3d, [[0, 1], [1, 2]])
print(result)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 3,  4],
       [11, 12]], dtype=int32)>

## boolean_mask

In [21]:
# tf.boolean_mask 用于根据布尔掩码从张量中选择特定的元素或切片
# 它的主要作用是通过布尔值过滤张量中的数据

# 示例 1：从 1D 张量中选择元素
# 创建一个 1D 张量
tensor_1d = tf.constant([1, 2, 3, 4, 5])
# 创建一个布尔掩码
mask_1d = tf.constant([True, False, True, False, True])
# 使用 tf.boolean_mask 选择元素
result_1d = tf.boolean_mask(tensor_1d, mask_1d)
print("从 1D 张量中选择的元素:")
print(result_1d)

从 1D 张量中选择的元素:
tf.Tensor([1 3 5], shape=(3,), dtype=int32)


In [24]:
# 示例 2：从 2D 张量中选择行
# 创建一个 2D 张量
tensor_2d = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# 创建一个布尔掩码
mask_2d = tf.constant([True, False, True])
# 使用 tf.boolean_mask 选择行
result_2d = tf.boolean_mask(tensor_2d, mask_2d, axis=0)
print("\n从 2D 张量中选择的行:")
print(result_2d)


从 2D 张量中选择的行:
tf.Tensor(
[[1 2 3]
 [7 8 9]], shape=(2, 3), dtype=int32)


In [23]:
# 示例 3：从 3D 张量中选择特定切片
# 使用之前定义的 tensor_3d
# 创建一个布尔掩码
mask_3d = tf.constant([True, False, True])
# 使用 tf.boolean_mask 选择矩阵
result_3d = tf.boolean_mask(tensor_3d, mask_3d, axis=0)
print("\n从 3D 张量中选择的矩阵:")
print(result_3d)


从 3D 张量中选择的矩阵:
tf.Tensor(
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[13 14]
  [15 16]
  [17 18]]], shape=(2, 3, 2), dtype=int32)
