# 索引和切片

In [1]:
import tensorflow as tf

# 创建一个 3x3 的张量
tensor = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("原始张量:")
print(tensor)

# 索引操作
# 获取第一行
first_row = tensor[0]
print("\n第一行:")
print(first_row)

# 获取最后一列
last_column = tensor[:, -1]
print("\n最后一列:")
print(last_column)

# 获取特定元素 (第二行，第三列)
specific_element = tensor[1, 2]
print("\n第二行第三列的元素:")
print(specific_element)

# 切片操作
# 获取前两行
first_two_rows = tensor[:2]
print("\n前两行:")
print(first_two_rows)

# 获取中间的 2x2 子张量
middle_subtensor = tensor[0:2, 1:3]
print("\n中间的 2x2 子张量:")
print(middle_subtensor)

# 使用步长进行切片
# 每隔一行和一列取一个元素
strided_tensor = tensor[::2, ::2]
print("\n步长为 2 的切片:")
print(strided_tensor)

原始张量:
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)

第一行:
tf.Tensor([1 2 3], shape=(3,), dtype=int32)

最后一列:
tf.Tensor([3 6 9], shape=(3,), dtype=int32)

第二行第三列的元素:
tf.Tensor(6, shape=(), dtype=int32)

前两行:
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

中间的 2x2 子张量:
tf.Tensor(
[[2 3]
 [5 6]], shape=(2, 2), dtype=int32)

步长为 2 的切片:
tf.Tensor(
[[1 3]
 [7 9]], shape=(2, 2), dtype=int32)


In [4]:
# 生成 TensorFlow 的张量
# 使用 tf.constant 创建一个 3x3 的张量
# 张量是 TensorFlow 中的基本数据结构，类似于多维数组
tensor = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("原始张量:")
print(tensor)

first_row = tensor[0]
print("\n第一行:")
print(first_row)
print("\n使用...:")
print(tensor[...])
print("\n使用 0, ...:")
print(tensor[0,...])
print("\n使用 ...,0:")
print(tensor[...,0])

原始张量:
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)

第一行:
tf.Tensor([1 2 3], shape=(3,), dtype=int32)

使用...:
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)

使用 0, ...:
tf.Tensor([1 2 3], shape=(3,), dtype=int32)

使用 ...,0:
tf.Tensor([1 4 7], shape=(3,), dtype=int32)


## tf.gather

In [9]:
import tensorflow as tf

# tf.gather 用于从张量的指定轴中根据索引提取切片
# 它的主要作用是从张量中提取特定的行、列或其他维度的子集

# 示例：从张量中提取特定的行或列

# 创建一个 3x3 的张量
tensor = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("原始张量:")
print(tensor)

原始张量:
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [10]:
# 使用 tf.gather 提取第 0 行和第 2 行
# 参数 axis=0 表示从行的维度提取
rows = tf.gather(tensor, indices=[0, 2], axis=0)
print("\n提取第 0 行和第 2 行:")
print(rows)


提取第 0 行和第 2 行:
tf.Tensor(
[[1 2 3]
 [7 8 9]], shape=(2, 3), dtype=int32)


In [ ]:
# 使用 tf.gather 提取第 1 列和第 2 列
# 参数 axis=1 表示从列的维度提取
columns = tf.gather(tensor, indices=[1, 2], axis=1)
print("\n提取第 1 列和第 2 列:")
print(columns)


提取第 1 列和第 2 列:
tf.Tensor(
[[2 3]
 [5 6]
 [8 9]], shape=(3, 2), dtype=int32)


In [15]:
# 示例：从 3D 张量中提取特定切片
tensor_3d = tf.constant([
  [[1, 2],   [3, 4],   [5, 6]],
  [[7, 8],   [9, 10],  [11, 12]],
  [[13, 14], [15, 16], [17, 18]]
])
print("\n3D 张量:")
print(tensor_3d)


3D 张量:
tf.Tensor(
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]], shape=(3, 3, 2), dtype=int32)


In [14]:
# 提取第 0 和第 2 个矩阵 (axis=0)
matrices = tf.gather(tensor_3d, indices=[0, 2], axis=0)
print("\n提取第 0 和第 2 个矩阵:")
print(matrices)



提取第 0 和第 2 个矩阵:
tf.Tensor(
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[13 14]
  [15 16]
  [17 18]]], shape=(2, 3, 2), dtype=int32)


In [12]:
# 提取每个矩阵的第 1 行 (axis=1)
rows_3d = tf.gather(tensor_3d, indices=[1], axis=1)
print("\n提取每个矩阵的第 1 行:")
print(rows_3d)


提取每个矩阵的第 1 行:
tf.Tensor(
[[[ 3  4]]

 [[ 9 10]]

 [[15 16]]], shape=(3, 1, 2), dtype=int32)


In [13]:
# 提取每行的第 0 列 (axis=2)
columns_3d = tf.gather(tensor_3d, indices=[0], axis=2)
print("\n提取每行的第 0 列:")
print(columns_3d)


提取每行的第 0 列:
tf.Tensor(
[[[ 1]
  [ 3]
  [ 5]]

 [[ 7]
  [ 9]
  [11]]

 [[13]
  [15]
  [17]]], shape=(3, 3, 1), dtype=int32)


## gather_nd

In [ ]:
# 使用 tf.gather_nd 提取张量 tensor_3d 中的特定位置的元素
# [0, 0] 表示提取第 0 个矩阵的第 0 行的第 0 列的元素
result = tf.gather_nd(tensor_3d, [0, 0])
print(result)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [ ]:
# 使用 tf.gather_nd 从 3D 张量中提取特定位置的元素
# [[0,1], [1,2]] 表示提取第 0 个矩阵的第 1 行和第 1 个矩阵的第 2 行
result = tf.gather_nd(tensor_3d, [[0, 1], [1, 2]])
print(result)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 3,  4],
       [11, 12]], dtype=int32)>

## boolean_mask

In [21]:
# tf.boolean_mask 用于根据布尔掩码从张量中选择特定的元素或切片
# 它的主要作用是通过布尔值过滤张量中的数据

# 示例 1：从 1D 张量中选择元素
# 创建一个 1D 张量
tensor_1d = tf.constant([1, 2, 3, 4, 5])
# 创建一个布尔掩码
mask_1d = tf.constant([True, False, True, False, True])
# 使用 tf.boolean_mask 选择元素
result_1d = tf.boolean_mask(tensor_1d, mask_1d)
print("从 1D 张量中选择的元素:")
print(result_1d)

从 1D 张量中选择的元素:
tf.Tensor([1 3 5], shape=(3,), dtype=int32)


In [24]:
# 示例 2：从 2D 张量中选择行
# 创建一个 2D 张量
tensor_2d = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# 创建一个布尔掩码
mask_2d = tf.constant([True, False, True])
# 使用 tf.boolean_mask 选择行
result_2d = tf.boolean_mask(tensor_2d, mask_2d, axis=0)
print("\n从 2D 张量中选择的行:")
print(result_2d)


从 2D 张量中选择的行:
tf.Tensor(
[[1 2 3]
 [7 8 9]], shape=(2, 3), dtype=int32)


In [23]:
# 示例 3：从 3D 张量中选择特定切片
# 使用之前定义的 tensor_3d
# 创建一个布尔掩码
mask_3d = tf.constant([True, False, True])
# 使用 tf.boolean_mask 选择矩阵
result_3d = tf.boolean_mask(tensor_3d, mask_3d, axis=0)
print("\n从 3D 张量中选择的矩阵:")
print(result_3d)


从 3D 张量中选择的矩阵:
tf.Tensor(
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[13 14]
  [15 16]
  [17 18]]], shape=(2, 3, 2), dtype=int32)


## [ b , 3, h , w]

- 在 TensorFlow 中，形状为 [b, 3, h, w] 的张量通常用于表示批量图像数据
- b 表示批量大小（batch size），即一次处理的图像数量
- 3 表示通道数（channels），通常是 RGB 图像的三个颜色通道
- h 表示图像的高度（height）
- w 表示图像的宽度（width）


In [1]:
import tensorflow as tf

# 示例：创建一个形状为 [2, 3, 4, 4] 的张量
# 表示 2 张 RGB 图像，每张图像的大小为 4x4
tensor = tf.random.uniform(shape=[2, 3, 4, 4], minval=0, maxval=255, dtype=tf.float32)
print("形状为 [b, 3, h, w] 的张量:")
print(tensor)

形状为 [b, 3, h, w] 的张量:
tf.Tensor(
[[[[198.86166    93.0143    146.62198    83.94598  ]
   [ 68.7011    177.83429    41.344883    3.6219049]
   [121.44617    15.62692    24.295288   44.223183 ]
   [ 91.24292    41.919106  149.02153    60.422413 ]]

  [[103.42887   222.47305   144.64359   199.4327   ]
   [ 29.123552  241.18546   253.17381   105.08233  ]
   [ 17.69331    31.246605   72.62261   202.60188  ]
   [ 43.11732    55.962517   65.226265  147.29225  ]]

  [[219.88187    29.539068  151.76566   230.2127   ]
   [ 36.39621    88.49856   152.38457   144.01178  ]
   [ 16.355448  161.20836   213.86273   109.23843  ]
   [220.67906    99.29755    81.44261   143.32573  ]]]


 [[[ 89.73513   229.87413   234.23758   208.0892   ]
   [145.21375    69.89436    63.910656  167.35402  ]
   [ 36.608604  252.18265   100.42156    35.372395 ]
   [183.61302   144.06787   123.98729    25.021597 ]]

  [[123.95047   105.85445   221.18619    83.00226  ]
   [228.34944   253.92946   100.45895    89.01108  ]
   

In [ ]:
# 应用 1：获取第一个批次的图像
first_batch = tensor[0]
print("\n第一个批次的图像:")
print(first_batch)


第一个批次的图像:
tf.Tensor(
[[[198.86166    93.0143    146.62198    83.94598  ]
  [ 68.7011    177.83429    41.344883    3.6219049]
  [121.44617    15.62692    24.295288   44.223183 ]
  [ 91.24292    41.919106  149.02153    60.422413 ]]

 [[103.42887   222.47305   144.64359   199.4327   ]
  [ 29.123552  241.18546   253.17381   105.08233  ]
  [ 17.69331    31.246605   72.62261   202.60188  ]
  [ 43.11732    55.962517   65.226265  147.29225  ]]

 [[219.88187    29.539068  151.76566   230.2127   ]
  [ 36.39621    88.49856   152.38457   144.01178  ]
  [ 16.355448  161.20836   213.86273   109.23843  ]
  [220.67906    99.29755    81.44261   143.32573  ]]], shape=(3, 4, 4), dtype=float32)


In [3]:
# 应用 2：获取所有图像的第一个通道
first_channel = tensor[:, 0, :, :]
print("\n所有图像的第一个通道:")
print(first_channel)


所有图像的第一个通道:
tf.Tensor(
[[[198.86166    93.0143    146.62198    83.94598  ]
  [ 68.7011    177.83429    41.344883    3.6219049]
  [121.44617    15.62692    24.295288   44.223183 ]
  [ 91.24292    41.919106  149.02153    60.422413 ]]

 [[ 89.73513   229.87413   234.23758   208.0892   ]
  [145.21375    69.89436    63.910656  167.35402  ]
  [ 36.608604  252.18265   100.42156    35.372395 ]
  [183.61302   144.06787   123.98729    25.021597 ]]], shape=(2, 4, 4), dtype=float32)


In [4]:
# 应用 3：对每张图像进行归一化处理
# 将像素值从 [0, 255] 缩放到 [0, 1]
normalized_tensor = tensor / 255.0
print("\n归一化后的张量:")
print(normalized_tensor)



归一化后的张量:
tf.Tensor(
[[[[0.77984965 0.36476195 0.5749881  0.3291999 ]
   [0.2694161  0.69738936 0.1621368  0.01420355]
   [0.47625947 0.06128204 0.09527564 0.17342424]
   [0.35781538 0.16438864 0.58439815 0.23695064]]

  [[0.4056034  0.8724433  0.56722975 0.782089  ]
   [0.11421001 0.94582534 0.9928385  0.41208756]
   [0.06938553 0.12253571 0.28479457 0.79451716]
   [0.16908753 0.21946084 0.25578928 0.5776167 ]]

  [[0.86228186 0.11583948 0.5951594  0.90279496]
   [0.14273024 0.34705317 0.5975865  0.5647521 ]
   [0.06413901 0.63218963 0.8386774  0.42838597]
   [0.86540806 0.38940215 0.3193828  0.56206167]]]


 [[[0.35190248 0.9014672  0.91857874 0.8160361 ]
   [0.5694657  0.27409554 0.25063002 0.6562903 ]
   [0.14356315 0.98895156 0.39381003 0.13871527]
   [0.72005105 0.56497204 0.48622465 0.09812391]]

  [[0.4860803  0.41511548 0.86739683 0.32549906]
   [0.895488   0.9958018  0.39395666 0.34906304]
   [0.9081845  0.35578263 0.879619   0.38019073]
   [0.63384235 0.5754937  0.5549308  0

In [5]:
# 应用 4：交换通道顺序为 [b, h, w, 3]（常用于与其他库兼容）
# TensorFlow 默认使用 [b, h, w, c] 格式
transposed_tensor = tf.transpose(tensor, perm=[0, 2, 3, 1])
print("\n交换通道顺序后的张量:")
print(transposed_tensor)


交换通道顺序后的张量:
tf.Tensor(
[[[[198.86166   103.42887   219.88187  ]
   [ 93.0143    222.47305    29.539068 ]
   [146.62198   144.64359   151.76566  ]
   [ 83.94598   199.4327    230.2127   ]]

  [[ 68.7011     29.123552   36.39621  ]
   [177.83429   241.18546    88.49856  ]
   [ 41.344883  253.17381   152.38457  ]
   [  3.6219049 105.08233   144.01178  ]]

  [[121.44617    17.69331    16.355448 ]
   [ 15.62692    31.246605  161.20836  ]
   [ 24.295288   72.62261   213.86273  ]
   [ 44.223183  202.60188   109.23843  ]]

  [[ 91.24292    43.11732   220.67906  ]
   [ 41.919106   55.962517   99.29755  ]
   [149.02153    65.226265   81.44261  ]
   [ 60.422413  147.29225   143.32573  ]]]


 [[[ 89.73513   123.95047    24.438738 ]
   [229.87413   105.85445    58.54425  ]
   [234.23758   221.18619   105.27371  ]
   [208.0892     83.00226   111.87989  ]]

  [[145.21375   228.34944   209.62305  ]
   [ 69.89436   253.92946     7.8693776]
   [ 63.910656  100.45895   132.46646  ]
   [167.35402    89.0

在 TensorFlow 中，张量的形状 `[b, 3, h, w]` 表示批量图像数据，其中：

- `b` 是批量大小（batch size），表示一次处理的图像数量。
- `3` 是通道数（channels），通常是 RGB 图像的三个颜色通道。
- `h` 是图像的高度（height）。
- `w` 是图像的宽度（width）。

要将形状 `[b, 3, h, w]` 转换为 `[b, h, w, c]`，需要交换维度的顺序，使通道数 `3` 移动到最后一维。可以使用 TensorFlow 的 `tf.transpose` 函数完成此操作。

代码示例：

```python
# 假设 tensor 的形状为 [b, 3, h, w]   ----->    [b, h, w, 3]
#                    [0, 1, 2, 3]   ----->    [0, 2, 3 ,1]
transposed_tensor = tf.transpose(tensor, perm=[0, 2, 3, 1])
print(transposed_tensor.shape)  # 输出形状为 [b, h, w, c]
```

在 `perm` 参数中，`[0, 2, 3, 1]` 表示将第 0 维保持不变，将第 2 维和第 3 维移到前面，将第 1 维（通道数）移动到最后一维。