# 广播机制简介：
- 广播（Broadcasting）是指在进行张量操作时，TensorFlow 会自动扩展较小的张量，使其与较大的张量具有相同的形状。
- 这种机制可以简化代码编写，避免手动调整张量的形状。


In [6]:
import tensorflow as tf

# 示例 1: 标量与张量的广播
# 创建一个张量
tensor_a = tf.constant([1, 2, 3], dtype=tf.float32)  # 形状为 (3,)
scalar_b = tf.constant(2.0, dtype=tf.float32)       # 标量，形状为 ()

# 广播机制会将标量扩展为与张量相同的形状
result_1 = tensor_a + scalar_b  # 等价于 [1+2, 2+2, 3+2]

print(" tensor_a + scalar_b")
print("示例 1 结果:", result_1.numpy())


 tensor_a + scalar_b
示例 1 结果: [3. 4. 5.]


In [11]:
# 示例 2: 不同形状张量的广播
# 创建两个张量
tensor_c = tf.constant([[1], [2], [3]], dtype=tf.float32)  # 形状为 (3, 1)
tensor_d = tf.constant([10, 20, 30], dtype=tf.float32)     # 形状为 (3,)

# 广播机制会将 tensor_c 扩展为 (3, 3)，tensor_d 扩展为 (3, 3)
result_2 = tensor_c + tensor_d  # 逐元素相加
print(f"tensor_c : {tensor_c.shape} \n {tensor_c.numpy()}")
print(f"tensor_d : {tensor_d.shape} \n {tensor_d.numpy()}")
print("示例 2 结果:\n", result_2.numpy())

tensor_c : (3, 1) 
 [[1.]
 [2.]
 [3.]]
tensor_d : (3,) 
 [10. 20. 30.]
示例 2 结果:
 [[11. 21. 31.]
 [12. 22. 32.]
 [13. 23. 33.]]


In [4]:
# 示例 3: 广播与矩阵运算结合
# 创建两个张量
matrix_e = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.float32)  # 形状为 (2, 3)
vector_f = tf.constant([1, 2, 3], dtype=tf.float32)               # 形状为 (3,)

# 广播机制会将 vector_f 扩展为 (2, 3)
result_3 = matrix_e * vector_f  # 逐元素相乘
print("示例 3 结果:\n", result_3.numpy())

示例 3 结果:
 [[ 1.  4.  9.]
 [ 4. 10. 18.]]



# 注意事项：
- 1. 广播机制要求两个张量的形状从后往前对齐，且每一维度要么相等，要么其中一个为 1。
- 2. 如果形状不满足广播规则，会抛出错误。

![Broadcasting](广播机制.png)