# 广播机制简介：
- 广播（Broadcasting）是指在进行张量操作时，TensorFlow 会自动扩展较小的张量，使其与较大的张量具有相同的形状。
- 这种机制可以简化代码编写，避免手动调整张量的形状。


In [6]:
import tensorflow as tf

# 示例 1: 标量与张量的广播
# 创建一个张量
tensor_a = tf.constant([1, 2, 3], dtype=tf.float32)  # 形状为 (3,)
scalar_b = tf.constant(2.0, dtype=tf.float32)       # 标量，形状为 ()

# 广播机制会将标量扩展为与张量相同的形状
result_1 = tensor_a + scalar_b  # 等价于 [1+2, 2+2, 3+2]

print(" tensor_a + scalar_b")
print("示例 1 结果:", result_1.numpy())


 tensor_a + scalar_b
示例 1 结果: [3. 4. 5.]


In [11]:
# 示例 2: 不同形状张量的广播
# 创建两个张量
tensor_c = tf.constant([[1], [2], [3]], dtype=tf.float32)  # 形状为 (3, 1)
tensor_d = tf.constant([10, 20, 30], dtype=tf.float32)     # 形状为 (3,)

# 广播机制会将 tensor_c 扩展为 (3, 3)，tensor_d 扩展为 (3, 3)
result_2 = tensor_c + tensor_d  # 逐元素相加
print(f"tensor_c : {tensor_c.shape} \n {tensor_c.numpy()}")
print(f"tensor_d : {tensor_d.shape} \n {tensor_d.numpy()}")
print("示例 2 结果:\n", result_2.numpy())

tensor_c : (3, 1) 
 [[1.]
 [2.]
 [3.]]
tensor_d : (3,) 
 [10. 20. 30.]
示例 2 结果:
 [[11. 21. 31.]
 [12. 22. 32.]
 [13. 23. 33.]]


In [4]:
# 示例 3: 广播与矩阵运算结合
# 创建两个张量
matrix_e = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.float32)  # 形状为 (2, 3)
vector_f = tf.constant([1, 2, 3], dtype=tf.float32)               # 形状为 (3,)

# 广播机制会将 vector_f 扩展为 (2, 3)
result_3 = matrix_e * vector_f  # 逐元素相乘
print("示例 3 结果:\n", result_3.numpy())

示例 3 结果:
 [[ 1.  4.  9.]
 [ 4. 10. 18.]]



# 注意事项：
- 1. 广播机制要求两个张量的形状从后往前对齐，且每一维度要么相等，要么其中一个为 1。
- 2. 如果形状不满足广播规则，会抛出错误。

![Broadcasting](广播机制.png)

## TensorFlow 中 Broadcasting 的条件与对齐方式

### Broadcasting 条件：
1. **从后往前对齐**：两个张量的形状需要从最后一个维度开始对齐。
2. **维度匹配规则**：
  - 如果两个张量在某个维度的大小相同，则该维度可以进行操作。
  - 如果其中一个张量在某个维度的大小为 1，则可以扩展为与另一个张量相同的大小。
  - 如果上述条件均不满足，则会抛出错误。

### 对齐方式：
- Broadcasting 会自动扩展较小的张量，使其形状与较大的张量匹配。
- 扩展的方式是将大小为 1 的维度沿该维度复制，直到匹配目标形状。

### 示例：
- 张量 A 的形状为 `(3, 1)`，张量 B 的形状为 `(3,)`：
  - 从后往前对齐：
   - A 的最后一维为 `1`，B 的最后一维为 `3`，满足广播条件。
   - A 会被扩展为 `(3, 3)`，然后与 B 进行逐元素操作。
- 张量 C 的形状为 `(2, 3)`，张量 D 的形状为 `(3,)`：
  - 从后往前对齐：
   - C 的最后一维为 `3`，D 的最后一维为 `3`，满足广播条件。
   - D 会被扩展为 `(2, 3)`，然后与 C 进行逐元素操作。

### 注意事项：
- Broadcasting 不会修改原始张量的形状，而是生成一个新的张量。
- 如果两个张量的形状完全不兼容，则会抛出错误。


## 隐式扩张

In [13]:
# 隐式扩展示例
# 创建两个形状不同的张量
tensor_x = tf.constant([[1, 2, 3]], dtype=tf.float32)  # 形状为 (1, 3)
tensor_y = tf.constant([[1], [2], [3]], dtype=tf.float32)  # 形状为 (3, 1)

# 隐式广播：TensorFlow 会自动扩展张量的形状
# tensor_x 会被扩展为 (3, 3)，tensor_y 也会被扩展为 (3, 3)
result_implicit = tensor_x + tensor_y  # 逐元素相加
print("隐式广播结果 (result_implicit):\n", result_implicit.numpy())

隐式广播结果 (result_implicit):
 [[2. 3. 4.]
 [3. 4. 5.]
 [4. 5. 6.]]


## 显式扩张 boradcast_to

In [14]:
# 显式扩展示例
# 使用 tf.broadcast_to 显式扩展张量的形状
tensor_z = tf.constant([1, 2, 3], dtype=tf.float32)  # 形状为 (3,)
broadcasted_tensor_z = tf.broadcast_to(tensor_z, [2, 3])  # 显式扩展为形状 (2, 3)

# 显式扩展后进行操作
matrix_w = tf.constant([[1, 1, 1], [2, 2, 2]], dtype=tf.float32)  # 形状为 (2, 3)
result_explicit = matrix_w * broadcasted_tensor_z  # 逐元素相乘
print("显式扩展结果 (result_explicit):\n", result_explicit.numpy())

显式扩展结果 (result_explicit):
 [[1. 2. 3.]
 [2. 4. 6.]]


## Broadcast VS Tile
### Tile 操作
- `tf.tile` 是 TensorFlow 中用于重复张量的操作。
- 它通过指定每个维度的重复次数，将原始张量扩展为更大的张量。

#### 使用场景
- 当需要手动扩展张量的形状以匹配另一个张量时，可以使用 `tf.tile`。
- 与广播不同，`tf.tile` 会显式地创建一个新的张量，而广播是隐式的。

#### 示例
假设有一个张量 `tensor_z`，形状为 `(3,)`：
```python
# 使用 tf.tile 将 tensor_z 重复 2 次（行方向）和 3 次（列方向）
tiled_tensor = tf.tile(tensor_z, [2, 3])  # 结果形状为 (6, 9)
print("tiled_tensor:\n", tiled_tensor.numpy())
```

#### 注意事项
- `tf.tile` 会显式地增加内存占用，因为它会创建一个新的张量。
- 广播机制更高效，但在某些情况下，`tf.tile` 更适合用于生成特定形状的张量。