# Tensorflow 运算符

## Tensor 的运算符和常用运算

TensorFlow 提供了丰富的运算符来操作张量，以下是一些常用的运算符及其应用示例：

### 1. 基本数学运算
- `tf.add`：加法
- `tf.subtract`：减法
- `tf.multiply`：乘法
- `tf.divide`：除法

In [11]:
import tensorflow as tf

# 创建两个张量
a = tf.constant([1, 2, 3], dtype=tf.float32)
b = tf.constant([4, 5, 6], dtype=tf.float32)

# 基本运算
add_result = tf.add(a, b)  # 加法
sub_result = tf.subtract(a, b)  # 减法
mul_result = tf.multiply(a, b)  # 乘法
div_result = tf.divide(a, b)  # 除法

print("加法结果:", add_result.numpy())
print("减法结果:", sub_result.numpy())
print("乘法结果:", mul_result.numpy())
print("除法结果:", div_result.numpy())

加法结果: [5. 7. 9.]
减法结果: [-3. -3. -3.]
乘法结果: [ 4. 10. 18.]
除法结果: [0.25 0.4  0.5 ]


### 2. 矩阵运算
- `tf.matmul`：矩阵乘法 @ 符号
- `tf.transpose`：矩阵转置
- `tf.linalg.inv`：矩阵求逆

In [19]:
# 创建矩阵
matrix1 = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
matrix2 = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

# 矩阵乘法
# matmul_result = tf.matmul(matrix1, matrix2)
matmul_result = matrix1 @ matrix2

# 矩阵转置
transpose_result = tf.transpose(matrix1)

print("矩阵乘法结果:\n", matmul_result.numpy())
print("矩阵转置结果:\n", transpose_result.numpy())

矩阵乘法结果:
 [[19. 22.]
 [43. 50.]]
矩阵转置结果:
 [[1. 3.]
 [2. 4.]]


### 3. 统计运算
- `tf.reduce_sum`：求和
- `tf.reduce_mean`：求均值
- `tf.reduce_max`：求最大值
- `tf.reduce_min`：求最小值

In [13]:
# 创建张量
tensor = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.float32)

# 统计运算
sum_result = tf.reduce_sum(tensor)  # 求和
mean_result = tf.reduce_mean(tensor)  # 求均值
max_result = tf.reduce_max(tensor)  # 求最大值
min_result = tf.reduce_min(tensor)  # 求最小值

print("总和:", sum_result.numpy())
print("均值:", mean_result.numpy())
print("最大值:", max_result.numpy())
print("最小值:", min_result.numpy())

总和: 21.0
均值: 3.5
最大值: 6.0
最小值: 1.0


### 4. 广播机制
TensorFlow 支持广播机制，可以对不同形状的张量进行运算。

In [14]:
# 广播机制示例
x = tf.constant([[1, 2, 3]], dtype=tf.float32)  # 形状为 (1, 3)
y = tf.constant([[1], [2], [3]], dtype=tf.float32)  # 形状为 (3, 1)

broadcast_result = tf.add(x, y)  # 广播加法

print("广播加法结果:\n", broadcast_result.numpy())

广播加法结果:
 [[2. 3. 4.]
 [3. 4. 5.]
 [4. 5. 6.]]


### 5. 激活函数
- `tf.nn.relu`：ReLU 激活函数
- `tf.nn.sigmoid`：Sigmoid 激活函数
- `tf.nn.tanh`：Tanh 激活函数

In [17]:
# 创建张量
z = tf.constant([-1.0, 0.0, 1.0], dtype=tf.float32)

# 激活函数
relu_result = tf.nn.relu(z)  # ReLU
sigmoid_result = tf.nn.sigmoid(z)  # Sigmoid
tanh_result = tf.nn.tanh(z)  # Tanh

print("ReLU 结果:", relu_result.numpy())
print("Sigmoid 结果:", sigmoid_result.numpy())
print("Tanh 结果:", tanh_result.numpy())

ReLU 结果: [0. 0. 1.]
Sigmoid 结果: [0.26894143 0.5        0.7310586 ]
Tanh 结果: [-0.7615942  0.         0.7615942]


### 6. TensorFlow 中的初等函数
TensorFlow 提供了许多初等函数用于数学计算，例如指数、对数、幂函数、三角函数等。以下是一些常用初等函数的介绍及其应用示例：
- `tf.math.exp`：计算指数
- `tf.math.log`：计算自然对数
- `tf.math.pow`：计算幂
- `tf.math.sqrt`：计算平方根
- `tf.math.sin`：计算正弦
- `tf.math.cos`：计算余弦
- `tf.math.tan`：计算正切

In [16]:
# TensorFlow 初等函数示例

# 指数函数
exp_result = tf.math.exp(a)  # 计算 e^a
print("指数函数结果 (e^a):", exp_result.numpy())

# 自然对数函数
log_result = tf.math.log(b)  # 计算 ln(b)
print("自然对数结果 (ln(b)):", log_result.numpy())

# 幂函数
pow_result = tf.math.pow(a, 2)  # 计算 a^2
print("幂函数结果 (a^2):", pow_result.numpy())

# 平方根函数
sqrt_result = tf.math.sqrt(b)  # 计算 b 的平方根
print("平方根结果 (sqrt(b)):", sqrt_result.numpy())

# 三角函数
sin_result = tf.math.sin(a)  # 计算正弦
cos_result = tf.math.cos(a)  # 计算余弦
tan_result = tf.math.tan(a)  # 计算正切

print("正弦结果 (sin(a)):", sin_result.numpy())
print("余弦结果 (cos(a)):", cos_result.numpy())
print("正切结果 (tan(a)):", tan_result.numpy())

指数函数结果 (e^a): [ 2.7182817  7.389056  20.085537 ]
自然对数结果 (ln(b)): [1.3862944 1.609438  1.7917595]
幂函数结果 (a^2): [1. 4. 9.]
平方根结果 (sqrt(b)): [2.        2.236068  2.4494898]
正弦结果 (sin(a)): [0.84147096 0.9092974  0.14112   ]
余弦结果 (cos(a)): [ 0.5403023  -0.41614684 -0.9899925 ]
正切结果 (tan(a)): [ 1.5574077  -2.1850398  -0.14254655]
