# Merge & Split
- concat
- split
- stack
- unstack
------
1. **张量合并**：
   - 使用 `tf.concat` 函数可以将多个张量沿指定轴合并。
   - 参数 `axis` 指定合并的维度，`axis=0` 表示沿行方向合并，`axis=1` 表示沿列方向合并。

2. **张量分割**：
   - 使用 `tf.split` 函数可以将一个张量分割为多个子张量。
   - 参数 `num_or_size_splits` 指定分割的数量或每个子张量的大小。
   - 参数 `axis` 指定分割的维度。

In [1]:
# 导入 TensorFlow
import tensorflow as tf

# 创建两个张量
tensor1 = tf.constant([[1, 2], [3, 4]])
tensor2 = tf.constant([[5, 6], [7, 8]])

In [2]:
# 合并张量（沿不同轴）
# axis=0 表示沿行方向合并（垂直合并）
concat_axis0 = tf.concat([tensor1, tensor2], axis=0)
print("沿轴0合并的结果：\n", concat_axis0.numpy())

# axis=1 表示沿列方向合并（水平合并）
concat_axis1 = tf.concat([tensor1, tensor2], axis=1)
print("沿轴1合并的结果：\n", concat_axis1.numpy())

沿轴0合并的结果：
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
沿轴1合并的结果：
 [[1 2 5 6]
 [3 4 7 8]]


In [3]:
# 分割张量
# 将张量分割为 2 个子张量，沿轴 0 分割
split_axis0 = tf.split(concat_axis0, num_or_size_splits=2, axis=0)
print("沿轴0分割的结果：")
for i, t in enumerate(split_axis0):
    print(f"子张量 {i}:\n", t.numpy())

# 将张量分割为 2 个子张量，沿轴 1 分割
split_axis1 = tf.split(concat_axis1, num_or_size_splits=2, axis=1)
print("沿轴1分割的结果：")
for i, t in enumerate(split_axis1):
    print(f"子张量 {i}:\n", t.numpy())

沿轴0分割的结果：
子张量 0:
 [[1 2]
 [3 4]]
子张量 1:
 [[5 6]
 [7 8]]
沿轴1分割的结果：
子张量 0:
 [[1 2]
 [3 4]]
子张量 1:
 [[5 6]
 [7 8]]


# 张量堆叠与拆分（Stack & Unstack） 
- creat new dim

## 1. **张量堆叠（Stack）**
- 使用 `tf.stack` 函数可以将多个张量沿新轴堆叠。
- 参数 `axis` 指定堆叠的维度，默认值为 `0`，表示在最外层添加一个新维度。

### 示例代码：

In [4]:
# 堆叠张量
stacked_tensor = tf.stack([tensor1, tensor2], axis=0)  # 沿轴0堆叠
print("沿轴0堆叠的结果：\n", stacked_tensor.numpy())

stacked_tensor_axis1 = tf.stack([tensor1, tensor2], axis=1)  # 沿轴1堆叠
print("沿轴1堆叠的结果：\n", stacked_tensor_axis1.numpy())

沿轴0堆叠的结果：
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
沿轴1堆叠的结果：
 [[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


## 2. **张量拆分（Unstack）**
- 使用 `tf.unstack` 函数可以将一个张量沿指定轴拆分为多个张量。
- 参数 `axis` 指定拆分的维度，默认值为 `0`。

### 示例代码：

In [5]:
# 拆分张量
unstacked_tensors = tf.unstack(stacked_tensor, axis=0)  # 沿轴0拆分
print("沿轴0拆分的结果：")
for i, t in enumerate(unstacked_tensors):
  print(f"子张量 {i}:\n", t.numpy())

unstacked_tensors_axis1 = tf.unstack(stacked_tensor_axis1, axis=1)  # 沿轴1拆分
print("沿轴1拆分的结果：")
for i, t in enumerate(unstacked_tensors_axis1):
  print(f"子张量 {i}:\n", t.numpy())

沿轴0拆分的结果：
子张量 0:
 [[1 2]
 [3 4]]
子张量 1:
 [[5 6]
 [7 8]]
沿轴1拆分的结果：
子张量 0:
 [[1 2]
 [3 4]]
子张量 1:
 [[5 6]
 [7 8]]


## 3. **应用场景**
- 堆叠操作常用于将多个张量合并为一个整体，便于批量处理。
- 拆分操作常用于将一个批量张量分解为单个样本，便于逐个处理。