# 数据统计
- Vector norm
- reduce_min max mean
- argmin argmax
- equal
- accuracy
- unique
---
## TensorFlow 中常用的 Vector Norm

在 TensorFlow 中，`tf.norm` 函数可以用来计算向量或矩阵的范数。以下是常用的向量范数及其公式：

#### 1. L1 范数 (Manhattan Norm)
L1 范数是向量中所有元素绝对值的和，公式如下：
$$
\|x\|_1 = \sum_{i=1}^n |x_i|
$$

在 TensorFlow 中可以通过以下方式计算：
```python
tf.norm(x, ord=1)
```

#### 2. L2 范数 (Euclidean Norm)
L2 范数是向量中所有元素平方和的平方根，公式如下：
$$
\|x\|_2 = \sqrt{\sum_{i=1}^n x_i^2}
$$

在 TensorFlow 中可以通过以下方式计算：
```python
tf.norm(x, ord=2)
```

#### 3. 无穷范数 (Infinity Norm)
无穷范数是向量中元素绝对值的最大值，公式如下：
$$
\|x\|_\infty = \max(|x_1|, |x_2|, \dots, |x_n|)
$$

在 TensorFlow 中可以通过以下方式计算：
```python
tf.norm(x, ord=np.inf)
```

#### 4. p 范数
p 范数是向量中所有元素绝对值的 p 次方和的 1/p 次方，公式如下：
$$
\|x\|_p = \left(\sum_{i=1}^n |x_i|^p\right)^{\frac{1}{p}}
$$

在 TensorFlow 中可以通过以下方式计算：
```python
tf.norm(x, ord=p)
```

#### 示例代码
以下是一个计算不同范数的示例代码：

In [20]:
import tensorflow as tf
import numpy as np

x = tf.constant([1.0, -2.0, 3.0])

# L1 范数
l1_norm = tf.norm(x, ord=1)

# L2 范数
l2_norm = tf.norm(x, ord=2)

# 无穷范数
inf_norm = tf.norm(x, ord=np.inf)

print("L1 Norm:", l1_norm.numpy())
print("L2 Norm:", l2_norm.numpy())
print("Infinity Norm:", inf_norm.numpy())

L1 Norm: 6.0
L2 Norm: 3.7416575
Infinity Norm: 3.0


----
## reduce_min、reduce_max 和 reduce_mean

在 TensorFlow 中，`tf.reduce_min`、`tf.reduce_max` 和 `tf.reduce_mean` 是常用的操作，用于对张量进行降维操作，计算最小值、最大值和平均值。以下是它们的介绍、公式和示例代码：

## 1. `tf.reduce_min`
`tf.reduce_min` 用于计算张量沿指定维度的最小值。

### 公式
给定张量 $ x $ ，沿维度 $ d $  计算最小值：
$$
\text{reduce\_min}(x, d) = \min(x, \text{axis}=d)
$$

### 示例代码

In [21]:
x = tf.constant([[1, 2, 3], [4, 5, 6]])
min_value = tf.reduce_min(x, axis=0)  # 沿列计算最小值
print("Reduce Min (axis=0):", min_value.numpy())

Reduce Min (axis=0): [1 2 3]


## 2. `tf.reduce_max`
`tf.reduce_max` 用于计算张量沿指定维度的最大值。

### 公式
给定张量 $ x $ ，沿维度 $ d $  计算最大值：
$$
\text{reduce\_max}(x, d) = \max(x, \text{axis}=d)
$$

### 示例代码

In [22]:
x = tf.constant([[1, 2, 3], [4, 5, 6]])
max_value = tf.reduce_max(x, axis=1)  # 沿行计算最大值
print("Reduce Max (axis=1):", max_value.numpy())

Reduce Max (axis=1): [3 6]


## 3. `tf.reduce_mean`
`tf.reduce_mean` 用于计算张量沿指定维度的平均值。

### 公式
给定张量 $ x $ ，沿维度 $ d $  计算平均值：
$$
\text{reduce\_mean}(x, d) = \frac{1}{N} \sum_{i=1}^N x_i
$$

### 示例代码

In [23]:
x = tf.constant([[1, 2, 3], [4, 5, 6]])
mean_value = tf.reduce_mean(x, axis=None)  # 计算全局平均值
print("Reduce Mean (global):", mean_value.numpy())

Reduce Mean (global): 3


### 总结
- `tf.reduce_min`：计算最小值
- `tf.reduce_max`：计算最大值
- `tf.reduce_mean`：计算平均值

通过指定 `axis` 参数，可以控制降维的方向。如果不指定 `axis`，则对整个张量进行操作。

---
## TensorFlow 中常用的 `tf.argmax` 和 `tf.argmin`

在 TensorFlow 中，`tf.argmax` 和 `tf.argmin` 是常用的操作，用于计算张量沿指定维度的最大值或最小值的索引。以下是它们的介绍、公式和示例代码：

### 1. `tf.argmax`
`tf.argmax` 用于计算张量沿指定维度的最大值的索引。

#### 公式
给定张量 $ x $ ，沿维度 $ d $ 计算最大值的索引：
$$
\text{argmax}(x, d) = \text{index of } \max(x, \text{axis}=d)
$$

#### 示例代码

In [24]:
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [25]:
# 沿列计算最大值的索引
argmax_col = tf.argmax(x, axis=0)
print("Argmax (axis=0):", argmax_col.numpy())

# 沿行计算最大值的索引
argmax_row = tf.argmax(x, axis=1)
print("Argmax (axis=1):", argmax_row.numpy())

Argmax (axis=0): [1 1 1]
Argmax (axis=1): [2 2]


### 2. `tf.argmin`
`tf.argmin` 用于计算张量沿指定维度的最小值的索引。

#### 公式
给定张量 $ x $ ，沿维度 $ d $ 计算最小值的索引：
$$
\text{argmin}(x, d) = \text{index of } \min(x, \text{axis}=d)
$$

#### 示例代码

In [26]:
# 沿列计算最小值的索引
argmin_col = tf.argmin(x, axis=0)
print("Argmin (axis=0):", argmin_col.numpy())

# 沿行计算最小值的索引
argmin_row = tf.argmin(x, axis=1)
print("Argmin (axis=1):", argmin_row.numpy())

Argmin (axis=0): [0 0 0]
Argmin (axis=1): [0 0]


In [27]:
### 输出示例
# 假设张量 `x` 的值为：
x = tf.constant([[1, 2, 3], [4, 5, 6]])
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

### 总结
- `tf.argmin` 用于计算最小值的索引。
- 通过指定 `axis` 参数，可以控制计算的方向：
  - `axis=0` 表示沿列计算。
  - `axis=1` 表示沿行计算。

---
## TensorFlow `tf.equal`

在 TensorFlow 中，`tf.equal` 是一个用于比较两个张量是否相等的操作。它会逐元素比较两个张量的值，并返回一个布尔类型的张量，表示每个位置上的值是否相等。

### 公式
给定两个张量 $ x $ 和 $ y $，`tf.equal` 的计算公式为：
$$
\text{equal}(x, y) = 
\begin{cases} 
\text{True}, & \text{if } x_i = y_i \\
\text{False}, & \text{if } x_i \neq y_i
\end{cases}
$$

### 示例代码
以下是一个使用 `tf.equal` 的示例代码：

```python
import tensorflow as tf

# 定义两个张量
x = tf.constant([1, 2, 3, 4])
y = tf.constant([1, 0, 3, 0])

# 比较两个张量是否相等
result = tf.equal(x, y)

print("Tensor x:", x.numpy())
print("Tensor y:", y.numpy())
print("Equal result:", result.numpy())
```

### 输出示例
假设 `x` 和 `y` 的值分别为 `[1, 2, 3, 4]` 和 `[1, 0, 3, 0]`，则输出为：
```
Tensor x: [1 2 3 4]
Tensor y: [1 0 3 0]
Equal result: [ True False  True False]
```

### 总结
- `tf.equal` 是逐元素比较操作，返回布尔类型的张量。
- 它常用于条件判断或过滤操作。

### 准确率 (Accuracy)

在机器学习和深度学习中，**准确率 (Accuracy)** 是一种常用的评估指标，用于衡量模型预测的正确性。它表示模型预测正确的样本数量占总样本数量的比例。

#### 公式
给定真实标签 $ y_{\text{true}} $ 和预测标签 $ y_{\text{pred}} $，准确率的计算公式为：
$$
\text{Accuracy} = \frac{\text{Number of Correct Predictions}}{\text{Total Number of Predictions}}
$$

或者可以表示为：
$$
\text{Accuracy} = \frac{\sum_{i=1}^N \mathbb{1}(y_{\text{true}, i} = y_{\text{pred}, i})}{N}
$$
其中：
- $ N $ 是样本总数。
- $ \mathbb{1}(\cdot) $ 是指示函数，当条件为真时取值为 1，否则为 0。


#### 总结
- **准确率** 是衡量模型性能的重要指标，适用于分类任务。
- 在 TensorFlow 中，可以通过 `tf.equal` 和 `tf.reduce_mean` 结合实现准确率的计算。

In [28]:
import tensorflow as tf

# 假设真实标签 (y_true) 和预测标签 (y_pred)
y_true = tf.constant([1, 0, 1, 1, 0, 1])  # 真实值
y_pred = tf.constant([1, 0, 1, 0, 0, 1])  # 预测值

# 逐元素比较预测值和真实值是否相等
correct_predictions = tf.equal(y_true, y_pred)

print("correct_predictions ",correct_predictions)

# 将布尔值转换为浮点数，并计算平均值
accuracy = tf.reduce_mean(tf.cast(correct_predictions, tf.float32))
count = tf.reduce_sum(tf.cast(correct_predictions, tf.int32))

print("Accuracy:", accuracy.numpy())
print("Total Count :", y_true.shape)
print("Right Count :", count.numpy())

correct_predictions  tf.Tensor([ True  True  True False  True  True], shape=(6,), dtype=bool)
Accuracy: 0.8333333
Total Count : (6,)
Right Count : 5


#### 输出示例
假设真实标签和预测标签分别为 `[1, 0, 1, 1, 0, 1]` 和 `[1, 0, 1, 0, 0, 1]`，则输出为：
```
Accuracy: 0.8333333
```

---
## TensorFlow 中的 `tf.unique`

在 TensorFlow 中，`tf.unique` 是一个用于找出张量中唯一元素的操作。它会返回一个包含唯一值的张量，以及每个输入值在唯一值张量中的索引。

### 公式
给定一个张量 $ x $，`tf.unique` 的计算公式为：
$$
\text{unique}(x) = \{x_i \mid x_i \text{ 是 } x \text{ 中的唯一值}\}
$$

返回结果包括：
1. 唯一值张量 $ y $。
2. 每个输入值在唯一值张量中的索引 $ idx $。

### 示例代码
以下是一个使用 `tf.unique` 的示例代码：

```python
import tensorflow as tf

# 定义一个张量
x = tf.constant([1, 2, 2, 3, 4, 4, 5])

# 计算唯一值及其索引
unique_values, indices = tf.unique(x)

print("Original Tensor:", x.numpy())
print("Unique Values:", unique_values.numpy())
print("Indices:", indices.numpy())
```

### 输出示例
假设输入张量为 `[1, 2, 2, 3, 4, 4, 5]`，则输出为：
```
Original Tensor: [1 2 2 3 4 4 5]
Unique Values: [1 2 3 4 5]
Indices: [0 1 1 2 3 3 4]
```

### 总结
- `tf.unique` 用于提取张量中的唯一值。
- 返回的索引可以用来重建原始张量或映射到唯一值张量。
- 它常用于数据去重或分类任务中的预处理步骤。