## 填充与复制
- pad
- tile

### TensorFlow 中 `tf.pad` 方法的使用示例

`tf.pad` 方法用于对张量的边界进行填充操作。它可以在张量的指定维度上添加额外的值（如零填充），以调整张量的形状。

#### 示例代码

In [2]:
import tensorflow as tf

# 创建一个 2x2 的张量
tensor = tf.constant([[1, 2], [3, 4]], dtype=tf.int32)

# 定义填充规则：在第一个维度前后各填充 1，在第二个维度前后各填充 2
paddings = tf.constant([[1, 1], [2, 2]])

# 使用 tf.pad 进行填充
padded_tensor = tf.pad(tensor, paddings, mode='CONSTANT', constant_values=0)

print("原始张量：")
print(tensor.numpy())

print("\n填充后的张量：")
print(padded_tensor.numpy())

原始张量：
[[1 2]
 [3 4]]

填充后的张量：
[[0 0 0 0 0 0]
 [0 0 1 2 0 0]
 [0 0 3 4 0 0]
 [0 0 0 0 0 0]]


#### 代码解释

1. **创建张量**: 使用 `tf.constant` 创建一个 2x2 的整数张量。
2. **定义填充规则**: `paddings` 是一个形状为 `[n, 2]` 的张量，其中 `n` 是待填充张量的维度数。每一行表示在对应维度的前后填充的大小。
  - `[1, 1]` 表示在第一个维度（行）前后各填充 1。
  - `[2, 2]` 表示在第二个维度（列）前后各填充 2。
3. **调用 `tf.pad`**:
  - `tensor`: 需要填充的张量。
  - `paddings`: 填充规则。
  - `mode`: 填充模式，这里使用 `'CONSTANT'` 表示常量填充。
  - `constant_values`: 填充值，这里填充 0。
4. **输出结果**: 填充后的张量形状为 `(4, 6)`，因为在原始张量的每个维度上都增加了填充。

### TensorFlow 中 `tf.tile` 方法的使用示例

`tf.tile` 方法用于对张量进行复制操作。它可以在指定的维度上重复张量的内容，从而扩展张量的形状。

#### 示例代码

In [3]:
# 使用 tf.tile 对张量进行复制
tiled_tensor = tf.tile(tensor, multiples=[2, 3])

print("原始张量：")
print(tensor.numpy())

print("\n复制后的张量：")
print(tiled_tensor.numpy())

原始张量：
[[1 2]
 [3 4]]

复制后的张量：
[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


#### 代码解释

1. **创建张量**: 这里使用了之前定义的 `tensor`，它是一个 2x2 的整数张量。
2. **调用 `tf.tile`**:
  - `tensor`: 需要复制的张量。
  - `multiples`: 一个列表或张量，表示每个维度上复制的次数。
    - `[2, 3]` 表示在第一个维度（行）上复制 2 次，在第二个维度（列）上复制 3 次。
3. **输出结果**: 
  - 原始张量形状为 `(2, 2)`。
  - 复制后的张量形状为 `(4, 6)`，因为在第一个维度上扩展为 `2 * 2 = 4`，在第二个维度上扩展为 `2 * 3 = 6`。