## 数据限幅 上下限
- clip_by_value
- relu / max min
- clip_by_norm
- gradient clip 

In [1]:
import tensorflow as tf

## tf.clip_by_value

In [3]:
# 示例1：使用 tf.clip_by_value 限幅

# 创建一个 2x3 的张量，其中包含一些超出上下限的值
tensor = tf.constant([[-10.0, 2.0, 30.0], [4.0, -50.0, 60.0]])

# 使用 tf.clip_by_value 对张量进行限幅操作
# clip_value_min=-5.0 表示最小值限制为 -5.0
# clip_value_max=10.0 表示最大值限制为 10.0
clipped_tensor = tf.clip_by_value(tensor, clip_value_min=-5.0, clip_value_max=10.0)

# 打印原始张量
print("Original Tensor:")  # 输出原始张量的值
print(tensor.numpy())  # 使用 .numpy() 将张量转换为 NumPy 数组以便打印

# 打印限幅后的张量
print("Clipped Tensor (by value):")  # 输出限幅后的张量的值
print(clipped_tensor.numpy())  # 使用 .numpy() 将张量转换为 NumPy 数组以便打印

Original Tensor:
[[-10.   2.  30.]
 [  4. -50.  60.]]
Clipped Tensor (by value):
[[-5.  2. 10.]
 [ 4. -5. 10.]]


## 2 relu max min

In [4]:
# 示例2：使用 tf.maximum 和 tf.minimum

# 使用 tf.maximum 将张量中的每个元素与一个最小值进行比较，取较大的值
min_value = -5.0
max_tensor = tf.maximum(tensor, min_value)

# 使用 tf.minimum 将张量中的每个元素与一个最大值进行比较，取较小的值
max_value = 10.0
min_tensor = tf.minimum(tensor, max_value)

# 打印使用 tf.maximum 和 tf.minimum 操作后的张量
print("Tensor after applying tf.maximum (min value -5.0):")
print(max_tensor.numpy())

print("Tensor after applying tf.minimum (max value 10.0):")
print(min_tensor.numpy())

Tensor after applying tf.maximum (min value -5.0):
[[-5.  2. 30.]
 [ 4. -5. 60.]]
Tensor after applying tf.minimum (max value 10.0):
[[-10.   2.  10.]
 [  4. -50.  10.]]


In [5]:
# 示例3：使用 tf.nn.relu

# 使用 tf.nn.relu 将张量中的负值替换为 0
relu_tensor = tf.nn.relu(tensor)

# 打印使用 tf.nn.relu 操作后的张量
print("Tensor after applying tf.nn.relu:")
print(relu_tensor.numpy())

Tensor after applying tf.nn.relu:
[[ 0.  2. 30.]
 [ 4.  0. 60.]]


## tf.clip_by_norm

`tf.clip_by_norm` 是 TensorFlow 中用于对张量进行范数限幅的方法。它通过将张量的 L2 范数限制在指定的最大值范围内，确保张量的值不会过大，从而避免梯度爆炸等问题。

### 示例：使用 `tf.clip_by_norm` 对张量进行范数限幅

以下是一个示例代码，展示如何使用 `tf.clip_by_norm`：

In [9]:
# 示例4：使用 tf.clip_by_norm

# 创建一个 2x3 的张量
tensor = tf.constant([[-10.0, 2.0, 30.0], [4.0, -50.0, 60.0]])

# 使用 tf.clip_by_norm 对张量进行范数限幅
# clip_norm=10.0 表示将张量的 L2 范数限制在 10.0 以内
clipped_norm_tensor = tf.clip_by_norm(tensor, clip_norm=10.0)

# 打印原始张量
print("Original Tensor:")
print(tensor.numpy())

# 打印范数限幅后的张量
print("Clipped Tensor (by norm):")
print(clipped_norm_tensor.numpy())

Original Tensor:
[[-10.   2.  30.]
 [  4. -50.  60.]]
Clipped Tensor (by norm):
[[-1.1851137   0.23702274  3.5553412 ]
 [ 0.4740455  -5.9255686   7.1106825 ]]


### 代码解释

1. **创建张量**：使用 `tf.constant` 创建一个包含多个值的张量。
2. **范数限幅**：调用 `tf.clip_by_norm` 方法，将张量的 L2 范数限制在指定的最大值（如 10.0）以内。
3. **打印结果**：
  - 原始张量：显示未经过限幅操作的张量。
  - 限幅后的张量：显示经过 `tf.clip_by_norm` 操作后的张量，其 L2 范数被限制在指定范围内。

-----
##  TensorFlow 中的梯度裁剪（Gradient Clipping）

梯度裁剪是一种在深度学习中常用的技术，用于防止梯度爆炸问题。梯度爆炸通常发生在深度神经网络（尤其是 RNN）中，梯度的值在反向传播过程中变得非常大，导致模型无法收敛。

TensorFlow 提供了多种梯度裁剪的方法，包括：
1. **按值裁剪**：使用 `tf.clip_by_value` 将梯度限制在指定的最小值和最大值之间。
2. **按范数裁剪**：使用 `tf.clip_by_norm` 将梯度的 L2 范数限制在指定范围内。
3. **全局范数裁剪**：使用 `tf.clip_by_global_norm` 对所有梯度的全局范数进行裁剪。

以下是一个使用梯度裁剪的示例代码：

In [10]:
# 示例：使用 tf.clip_by_global_norm 进行梯度裁剪

# 假设我们有一个简单的模型和损失函数
model = tf.keras.Sequential([
  tf.keras.layers.Dense(10, activation='relu'),
  tf.keras.layers.Dense(1)
])

# 创建一个优化器
optimizer = tf.keras.optimizers.Adam()

# 定义一个简单的损失函数
loss_fn = tf.keras.losses.MeanSquaredError()

# 创建一些示例输入数据和标签
x = tf.random.normal(shape=(5, 3))
y = tf.random.normal(shape=(5, 1))

# 使用 GradientTape 计算梯度
with tf.GradientTape() as tape:
  predictions = model(x)
  loss = loss_fn(y, predictions)

# 获取模型的可训练变量
trainable_vars = model.trainable_variables

# 计算梯度
gradients = tape.gradient(loss, trainable_vars)

# 对梯度进行全局范数裁剪
clipped_gradients, _ = tf.clip_by_global_norm(gradients, clip_norm=1.0)

# 使用裁剪后的梯度更新模型参数
optimizer.apply_gradients(zip(clipped_gradients, trainable_vars))

# 打印裁剪后的梯度
print("Clipped Gradients:")
for grad in clipped_gradients:
  print(grad.numpy())

Clipped Gradients:
[[-8.79968181e-02  3.44668739e-02  1.86334714e-01 -1.01161242e-01
  -5.92580251e-02  1.70760900e-01  3.88911983e-04  2.49473453e-02
  -1.32606560e-02  1.68541029e-01]
 [ 1.01195471e-02  2.12006737e-02 -2.88916315e-04 -6.22245781e-02
  -3.64497863e-02 -9.25172470e-04  4.69784689e-04  1.16571737e-02
  -1.60181541e-02  5.02109490e-02]
 [-8.94954279e-02  3.75109203e-02  1.53087646e-01 -1.10095605e-01
  -6.44915849e-02  2.36729577e-01  1.63215023e-04 -1.30668581e-02
  -5.56511013e-03  1.72641158e-01]]
[-0.10037925  0.09631145  0.3728942  -0.2826768  -0.16558586  0.28433126
 -0.00141477  0.01404836  0.04823916  0.3012443 ]
[[-0.09686241]
 [-0.02893383]
 [-0.14626284]
 [-0.01541002]
 [-0.00344976]
 [-0.07881485]
 [ 0.04318966]
 [-0.0272631 ]
 [ 0.04280951]
 [-0.0688723 ]]
[-0.5032773]
